### ISSUE TITLE
Convert to DM

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#122]
Provide a conversion from EDS or MRS to DM.

**Comment by ZhaofengWu** [comment]
Hi, I'm wondering if there's any update on this. If not, do you know of any other tool that can convert MRS produced by ACE to DM? Looks like I can query a DM representation from the REST interface, but not ACE.

**Comment by goodmami** [comment]
@ZhaofengWu thanks for your interest, but I don't currently have this slated for an upcoming release. I'd be happy to have it, but it's not currently a priority.

The LOGON system is now able to convert to DM from the commandline. See this thread: http://lists.delph-in.net/archives/developers/2019/002883.html (link is the final message)

But you will probably need to download the entire LOGON tree, which is ~4.6GB of mostly irrelevant packages. See here: http://moin.delph-in.net/LogonInstallation

That said I think PyDelphin has most of the capability to implement DM conversion itself (such as the ability to read .tdl lexicons, read SEM-I files, and convert to EDS), so

**Comment by ZhaofengWu** [comment]
Thank you for the response! If I need to parse a pretty big corpus to DM using an ERG-based parser, is PyDelphin's ACE parser + the LOGON DM converter that you mentioned my best bet? Even though DM is available via the RESTful service, it is extremely slow and sometimes unstable for a big corpus.

**Comment by goodmami** [comment]
That would work. The RESTful interface is not well-suited for processing large corpora. You can use PyDelphin's ACE interface, or use ACE directly with `art` (http://sweaglesw.org/linguistics/libtsdb/art), or you can use LOGON for parsing as well (see http://moin.delph-in.net/LogonProcessing/BatchParsing)

**Comment by ZhaofengWu** [comment]
When you said "link is the final message", which link were you referring to? Is it http://moin.delph-in.net/ErgApi? I can't seem to find the `--export` option that they are talking about. Could you point me to the specific command that converts MRS to DM? Thank you!

**Comment by goodmami** [comment]
Sorry, I just meant that the mailing list message I linked to (http://lists.delph-in.net/archives/developers/2019/002883.html) is the final message in its thread. So you may want to look at other messages in the thread, but I think all the information is in that message (in the new and quoted parts of the reply).

I'm afraid I don't know any more about the `--export` option than what's in that thread, and I don't know how to call the `redwoods` script (though I see some examples here: http://moin.delph-in.net/RedwoodsLpp). I suggest emailing the developers list for more help. See here about subscribing to the list: http://lists.delph-in.net/mailman/listinfo/developers

**Comment by arademaker** [comment]
Hi @goodmami, just to update this issue. I was not able to use redwoods script with the option to export DM. It is not even clear to me what it does. If I understood right, it just calls the python dtm.py script in the Logon distribution. This script read the .gz files exported from a profile to produce a conll-like file. 

I am not reading the references listed in http://alt.qcri.org/semeval2014/task8/index.php?id=dependency-formats to understand how difficult would be to implement the DM transformation from EDS using the PyDelphin already available code.

**Comment by goodmami** [comment]
Thanks. I have also looked over the `$LOGONROOT/uio/dtm/converter.py` script and found it hard to work out. I read through the methodology chapter/section of Angelina's thesis and the LAW 2012 paper and it felt like there were major gaps for reproducibility, but maybe I need to more carefully read other sections, too. Even if we work out the general procedure, there are ERG-specific features that pertain to an older version of the ERG, so we'd have to somehow account for those across multiple versions (or just update them to the latest?). So overall I'm not enthusiastic about trying to recreate the representation. If someone could shed light on the proper procedure I'd be more willing to give it a second (third... maybe fourth) look.

**Comment by goodmami** [comment]
I'm going to close this issue. It's been years without any activity and I don't have the time or willingness to work out a LOGON-less way to do conversion to DM that isn't tied to a specific version of the ERG. I'm happy to review a PR if someone else comes along and does it, though!
