### ISSUE TITLE
Improve error message when ACE fails to start

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#181]
Instantiating an AceProcessor with an old grammar image currently results in a stack trace with the error "Broken pipe" which hides the error from ACE. The `delphin.interfaces.ace.AceProcess._open()` method should check if the opened process terminated and raise a more appropriate error (this may require a new exception class in `delphin.exceptions`)

**Comment by mcmillanmajora** [comment]
I think I have a solution for this by checking if the ``Popen`` object's ``poll()`` value is not ``None``, but I'm not sure what kind of file I would need write to replicate an old grammar image for testing.

**Comment by goodmami** [comment]
Good :) And that sounds about right. Checking the `poll()` value is how I detect crashes in the `_result_lines()` method of `AceProcess`. As for testing, look how I use `monkeypatch` (a pytest thing) to override stdin in `tests/commands_test.py`. You can use this pattern with the expected output from ACE (the "version mismatch..." line below). It would be nice if you could also override the return code (shown by the $? variable in bash), but I'm not sure offhand how to do that.

```
goodmami@tpy:~/grammars$ ace -g erg-1214-x86-64-0.9.27.dat 
version mismatch: this is ACE version 0.9.29, but this grammar image was compiled by ACE version 0.9.27
goodmami@tpy:~/grammars$ echo "$?"
255
```

Also, I'm not sure if you've looked at the `v1.0.0` branch yet, but I've moved to have a fairly minimal `delphin.exceptions` with module-specific exceptions defined in the modules themselves (in case you created a custom exception for this ACE error). Let me know if you have questions about this.

**Comment by goodmami** [comment]
Assigning to myself. I have a fix in my branch.
