### ISSUE TITLE
Process full-forest profiles

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#201]
PyDelphin supports 4 or 5 output modes from ACE: regular parsing, transfer, and generation, and the `--tsdb-stdout` mode for parsing and generation.

The output mode for building full-forest profiles is yet another one, instantiated by the `-O` option. Currently, this mode ignores `--tsdb-stdout` for the results (but it does output run and input information, just not edges and tokens, in s-expressions). I need some more information about the output format before I can attempt an implementation.

**Comment by goodmami** [comment]
It turns out the `--itsdb-forest` option, in conjuction with `--tsdb-stdout` and *without* `-O`, will output edges as s-expressions, which should be trivial to populate a profile with.

Thanks to Woodley for pointing this out.

**Comment by arademaker** [comment]
Not sure if make sense to add it here, but it is not clear how to specifiy arguments for ACE using the process command. For instance, how can I say that I want `n` analyses ? 

```
$ delphin process –help
usage: delphin process [-h] [-v] [-q] -g GRM [-s PATH] [--select QUERY]
                       [--all-items] [-e | -t] [-p RID]
                       TESTSUITE
delphin process: error: the following arguments are required: -g/--grammar
```

**Comment by goodmami** [comment]
That is what #180 was for. The issue is resolved because the functionality is implemented in the 'develop' branch, but you're using the latest release which does not include it. When I get around to releasing v0.9.2 it will be included then, but lately I've been working on a different deadline with Francis.

**Comment by arademaker** [comment]
Sure, my mistake on repeating it here. Sorry.

**Comment by goodmami** [comment]
No worries. The other issue is "closed", so it doesn't appear in the [issues list](https://github.com/delph-in/pydelphin/issues/) unless you go looking for it.

**Comment by arademaker** [comment]
Hi @goodmami , does it mean that we can make the profile for FFTB using pydelphin? If so, why did I get:

```
404 no stored forest found for this item
```

in the `fftb` once I clicked in a sentence in a profile processed with: 

```
$ cat process-fftb.py
from delphin import ace
from delphin import tsdb
from delphin import itsdb

ts = itsdb.TestSuite('sample-200')
opts = ['-n','1','--rooted-derivations','--disable-generalization']
with ace.ACEParser('terg.dat', cmdargs = opts) as cpu:
    ts.process(cpu)
```
