### ISSUE TITLE
REPP in NLTK

### ISSUE THREAD

**Issue by alvations** [delph-in/pydelphin#202]
Thanks Mike for reimplementing the [REPP tokenizer](https://github.com/delph-in/pydelphin/blob/develop/delphin/repp.py) !

@Rebecca, if you're following this, if it's alright, could we deprecate the wrapper that we have in NLTK?

I think we would like to put `pydelphin` as an optional dependency when people wants to use REPP. Like how SpaCy has been doing it for several other tools. 

@goodmami One issue though, are there default REPP rules that we can add into `nltk_data` and we'll try to load them as the default?

**Comment by goodmami** [comment]
@alvations I'd be happy to have the code be available in NLTK. Even though `repp.py` is a small and relatively isolated part of PyDelphin, maybe a blanket dependency (rather than a repackaged `repp.py`) would make sense, since PyDelphin is a relatively small codebase and we may want to offer other components in the future.

Regarding the default REPP rules, I think the ERG's default rules make sense, but I'm not sure how the licensing would work. Maybe they could be downloaded separately. Or we could just put in a very basic single-file tokenizer with instructions and links for using others.

(And is that Bec's GitHub username? I'm not sure she's got an account)

**Comment by goodmami** [comment]
I'm closing this as it should be an issue for the NLTK rather than PyDelphin. Feel free to reopen if there are things PyDelphin needs to do in order to make it happen.

**Comment by arademaker** [comment]
Hi @goodmami , just a broad question. What was the motivation for the REPP implementation in PyDelphin? REPP rules are used executed by the parsers, right? I mean, Ace, LKB or Pet, right? Another question is, If I understood right, the rules are grammar specific right?

**Comment by goodmami** [comment]
The tokenization rules and the grammar are developed in tandem, I think. That is, the grammar's lexicon and lexical rules are adapted to the expected tokenization, and the tokenization patterns are adjusted to make life easier for the grammar.

However the tokenizer can be used outside of a grammar. Yes, the patterns are usually part of the grammar's repository and are called by processors (ACE, LKB, PET) during parsing, but they are not dependent on the rest of the grammar. REPP can be a general-purpose tokenizer. And it's character span tracking is a unique (AFAIK) feature.

There are several reasons why I implemented REPP in PyDelphin:

* It helps me understand what exactly REPP does and how the other implementations are different
* The LKB and ACE versions do not give correct surface alignments (characterization); and even the PET/C++ version do not in one specific instance (see [here](http://lists.delph-in.net/archives/developers/2019/002999.html))
* Unlike other implementations, I provide a [trace](https://pydelphin.readthedocs.io/en/latest/api/delphin.repp.html#delphin.repp.REPP.trace) feature which can help with debugging REPP rules; this is particularly nice with the [`delphin repp`](https://pydelphin.readthedocs.io/en/latest/guides/commands.html#repp) command
* In implementing it for PyDelphin, I provide fairly clean, tested, documented, and easily-available code

It seems that your group, at least, has [found it useful](https://github.com/own-pt/sensetion.el/blob/0c140f8888b269e7e4791fe58f06a6888c2cc6c7/utils/touch.py#L4).

**Comment by arademaker** [comment]
I don't have any doubt it is useful, but this explanation was very useful for me.
