### ISSUE TITLE
Pred class documentation

### ISSUE THREAD

**Issue by arademaker** [delph-in/pydelphin#206]
https://pydelphin.readthedocs.io/en/latest/api/delphin.mrs.components.html#delphin.mrs.components.Pred

1. what is the real-preds? what is the difference between real-preds and surface preds?
2. what is a quoted pred?

This paragraph is strange

> In PyDelphin, Preds are equivalent if they ... are both abstract or both surface preds. Other factors are ignored for comparison, such as their being surface-, abstract-, or real-preds...

First it says that preds are equivalent if they are both abstract or both surface. The next sentence say that their types are ignored in the comparation!

**Comment by goodmami** [comment]
Yes, the documentation is confusing here. 

"Real preds" sometimes are synonymous with "surface preds" (see [here](http://moin.delph-in.net/PredicateRfc#Surface_and_Abstract_Predicates)), but in PyDelphin they specifically refer to the 3-part decomposed form of a surface predicate (see [here](http://moin.delph-in.net/PredicateRfc#real-vs-surface)). It pretty-much only appears in MRX (XML): `<realpred lemma="dog" pos="n" sense="1" />` corresponds to the symbol `_dog_n_1`. In theory the parts can be modified, e.g., for resolving underspecified predicates (e.g., where `_blue_u_1` becomes `_blue_n_1` in "Blue is a color" or `_blue_a_1` in "The car is blue".... I think), but I haven't seen this done in practice.

PyDelphin underwent a change in terminology and it seems there was an overzealous search-and-replace. There used to be a string-pred vs grammar-pred distinction and it wasn't completely orthogonal from the surface vs abstract distinction. What the docs are trying to say is that these are the same:

* `"_dog_n_1_rel"` (quoted lower-case surface pred with `_rel`)
* `"_DOG_n_1"` (quoted mixed-case surface pred without `_rel`)
* `_dog_n_1` (unquoted lower-case surface predicate without `_rel`)
* `<realpred lemma="dog" pos="n" sense="1" />` (realpred decomposed form)

but these are different from the above:

* `"dog_n_1_rel"` (quoted abstract)
* `dog_n_1_rel` (unquoted abstract)
* `_dawg_n_1` (different lemma)
* `_dog_v_1` (different pos)
* `_dog_n_2` (different sense)

The v1.0.0 version of PyDelphin *may* do away with a Pred class and just use strings, in which case predicate comparison is done on a normalized string, but I haven't decided yet. Opinions regarding this are welcome.
