### ISSUE TITLE
Provide API access to something like ParseResult.tree()

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#208]
When using the ACE or HTTP interfaces we can call [ParseResult.tree()](https://pydelphin.readthedocs.io/en/latest/api/delphin.interfaces.html#delphin.interfaces.base.ParseResult.tree) to get an interpreted structure for the labeled trees, but when inspecting [incr tsdb()] testsuites there is no similar interface, and the `SExpr.parse()` functionality in `delphin.util` is undocumented (and not very user-friendly).

Some solutions might be:

1. create a `delphin.trees` module for this
2. create a function to parse trees in `delphin.derivation` (though it's not exactly a derivation)
3. make an `delphin.interface`-like view for [incr tsdb()] results

(1) is probably the most general solution, since (3) only solves the problem for [incr tsdb()] profiles. I don't really like (2) but I also don't want to create a module for a single function.

See here for some context: https://delphinqa.ling.washington.edu/t/pos-label-output-in-pydelphin/221/23

**Comment by goodmami** [comment]
I went with option (3) since that was needed anyway. If (1) is needed later it is easy to add; it's harder to remove.

In order to get a tree object from a test suite, the result.tree field must be filled. There is not much of a way around this. If I could dig into the feature structures on derivation trees I could get the TNT tag to reconstruct the tree maybe, but (a) I don't currently parse those feature structures and doing so would be a bit of work and (b) it's only for the ERG anyway.

**Comment by arademaker** [comment]
Why is it only for ERG?

**Comment by goodmami** [comment]
What I implemented is not only for the ERG. The method I described in that comment, but did not implement, would get the tree labels from the feature structures on the derivation tree, and I've only seen those on ERG derivations:

```
(0 sb-hd_mc_c 0.000000 0 2
  (0 it 0.000000 0 1
    ("it" 46 "token [ +FORM \\"it\\" +FROM \\"0\\" +TO \\"2\\" +ID *diff-list* [ LIST *list* LAST *list* ] +TNT null_tnt [ +TAGS *null* +PRBS *null* +MAIN tnt_main [ +TAG \\"PRP\\" +PRB \\"1.0\\" ] ] +CLASS alphabetic [ +CASE capitalized+lower +INITIAL + ] +TRAIT token_trait [ +UW - +IT italics +LB bracket_null [ LIST *list* LAST *list* ] +RB bracket_null [ LIST *list* LAST *list* ] +LD bracket_null [ LIST *list* LAST *list* ] +RD bracket_null [ LIST *list* LAST *list* ] +HD token_head [ +TI \\"<0:2>\\" +LL ctype [ -CTYPE- string ] +TG string ] ] +PRED predsort +CARG \\"It\\" +TICK + +ONSET c-or-v-onset ]"))
  (0 w_period_plr 0.000000 1 2
    (0 v_pst_olr 0.000000 1 2
      (0 rain_v1 0.000000 1 2
        ("rained." 44 "token [ +FORM \\"rained.\\" +FROM \\"3\\" +TO \\"10\\" +ID *diff-list* [ LIST *list* LAST *list* ] +TNT null_tnt [ +TAGS *null* +PRBS *null* +MAIN tnt_main [ +TAG \\"VBD\\" +PRB \\"1.0\\" ] ] +CLASS alphabetic [ +CASE non_capitalized+lower +INITIAL - ] +TRAIT token_trait [ +UW - +IT italics +LB bracket_null [ LIST *list* LAST *list* ] +RB bracket_null [ LIST *list* LAST *list* ] +LD bracket_null [ LIST *list* LAST *list* ] +RD bracket_null [ LIST *list* LAST *list* ] +HD token_head [ +TI \\"<3:10>\\" +LL ctype [ -CTYPE- string ] +TG string ] ] +PRED predsort +CARG \\"rained\\" +TICK + +ONSET c-or-v-onset ]")))))
```

Compare to a Jacy derivation:

```
(utterance-root
  (91 utterance_rule-decl-finite -0.723739 0 4
    (90 head_subj_rule -1.05796 0 4
      (87 hf-complement-rule -0.50201 0 2
        (86 quantify-n-rule -0.32216 0 1
          (5 ame-noun 0 0 1
            ("雨" 1 "\\"雨\\"")))
        (6 ga 0.531537 1 2
          ("が" 2 "\\"が\\"")))
    (89 vstem-vend-rule -0.471785 2 4
      (88 t-lexeme-c-stem-infl-rule 0.120963 2 3
        (14 furu_1 0 2 3
          ("降っ" 3 "\\"降っ\\"")))
      (24 ta-end -0.380719 3 4
        ("た" 4 "\\"た\\""))))))
```

But actually now that I look closer, I'm reminded that only the terminals have those feature structures and the tags are only POS tags on surface tokens, so it wouldn't even work for the ERG.

So we would need to extend the [UDX](http://moin.delph-in.net/ItsdbDerivations) format to include an optional `label` field on each node. Note that the JSON serialization of derivations does include labels, and PyDelphin uses that (if it's available) to extract the labeled parse tree.
