### ISSUE TITLE
Add --no-lnk option to convert command

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#216]
Similar to `--no-properties`, adding a `--no-lnk` option to the `convert` command to omit lnk surface alignments would be convenient to use and straightforward to implement.

**Comment by arademaker** [comment]
What are the lnk surface alignments ?

**Comment by goodmami** [comment]
`lnk` is just the abbreviation used in the LKB source and elsewhere of the mechanism for "linking", or aligning, MRS bits to the input string. It is exemplified several times on this wiki: http://moin.delph-in.net/MrsRfc

Also it's what you see after predicates, e.g., in `_surface_n_1<2:9>` the lnk value is `2:9` which means the predication is aligned to the input from character 2 up to (not including) character 9. Sometimes these two positions are referred to as `cfrom` and `cto`, respectively.

**Comment by arademaker** [comment]
thank you, this information is many times called the span. We actually have an entire page about it http://moin.delph-in.net/RmrsSpan not mentioning the term “link”

**Comment by goodmami** [comment]
Thanks, I forgot about that wiki. I think it could be deleted or archived as it is no longer relevant.

While "span" is an informal term denoted by the range of `cfrom` to `cto` values (and some people say "cfrom/cto span"), "lnk" is the more technical jargon used for the mechanism itself (like you might say "XPath selection" or "HTTP connection" where "Xpath" and "HTTP" are the mechanisms here). I've started calling it "Lnk surface alignments" instead of "Lnk span" because "surface alignment" seems common in our field for what it does, and besides it is more precise. Furthermore, Lnk can encode other kinds of alignments beyond character spans, although they are not widely used. Also note that "lnk" (without the "i") is not a typo; that's how it is spelled, but either way it doesn't show up in the RmrsSpan wiki.

Also, that wiki was only edited (meaningfully) once, when Francis created it in 2006. The Lnk mechanism started being used and documented around 2004 (see here: http://moin.delph-in.net/LkbEvolution). In the RmrsSpan wiki, Francis was arguing to move from the then-current implementation of using character "positions" to the more-useful "points", as what Perl and Python use for string slicing. E.g., `<0:2>` of `undo` is `un` and not `und`. This has some useful properties. Assume you have a token starting at point `s` and ending at `e`, then:
  * for any point `i` such that `s <= i <= e`, it will be true that `<s:i>` + `<i:e>` == `<s:e>`
  * `e` &minus; `s` is the length of the span
  * `<i:i>` is a 0-length span for any `i`

**Comment by goodmami** [comment]
Resolved via bd43c229bb0b746d0da26208ea31be7242699dc8

**Comment by arademaker** [comment]
yet another way to say:

[1]	E. Nichols, F. Bond, and D. Flickinger, “Robust Ontology Acquisition from Machine-Readable Dictionaries,” presented at the International Joint Conference on Artificial Intelligence, 2005, pp. 1111–1116.

> In order to simplify the combination of different analyses, the results are **indexed** to the position in the original input sentence.

**Comment by goodmami** [comment]
@arademaker thanks! and another that Stephan likes to use is "characterization", but I don't think that term is very clear.
