### ISSUE TITLE
Better handle unknown predicates in IndexedMRS

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#218]
Unknown predicates have a certain shape, e.g., "Every foo sleeps" leads to a `_foo/nn_u_unknown` predicate, but the predicates do not appear in a SEM-I, so the IndexedMRS codec can't handle them. Maybe there's a generic predicate we can find to map a synopsis.

Fixing this has low priority.

**Comment by arademaker** [comment]
> predicates do not appear in a SEM-I, so the IndexedMRS codec can't handle them. 

hum, a little bit of more details here would help to fully understand the issue.

**Comment by goodmami** [comment]
> hum, a little bit of more details here would help to fully understand the issue. ;-)

See [here](http://moin.delph-in.net/SemiRfc#predicates) and [here](http://moin.delph-in.net/MrsRfc#Indexed).

**Comment by goodmami** [comment]
I won't be fixing this any time soon.

**Comment by arademaker** [comment]
Instead of close these issues, can we mark them as "postponed"?

**Comment by goodmami** [comment]
> Instead of close these issues, can we mark them as "postponed"?

No, I don't want to give the impression that this is something I plan to do. If, however, you provide a PR, we can re-open the ticket and link it to the PR.
