### ISSUE TITLE
Convert DM to EDS

### ISSUE THREAD

**Issue by wangxinyu0922** [delph-in/pydelphin#235]
Hi, is it possible to convert DM to EDS structure? And I wonder how to convert EDS to DM now, as the I cannot find delphin.dm method in pydelphin. I want to learn some rules in converting EDS to DM, any suggestion for this? thank you!

**Comment by goodmami** [comment]
Converting from EDS to DM is lossy I think, so I'm not aware of any tools that convert from DM to EDS. For the same reason, EDS to MRS is not done (that I'm aware of), although Stephan Oepen has worked with generating text from EDS so he may have had some success.

Also, PyDelphin does not convert to DM, but please subscribe to #122 if you are interested. I don't expect to work on that anytime soon, but I would welcome such contributions :) Also see the comments in that issue for some links to mailing list threads about EDS->DM conversion, and also see the code here: http://svn.emmtee.net/trunk/uio/dtm/

@ZhaofengWu have you had any success in converting to DM?

**Comment by ZhaofengWu** [comment]
I didn't -- I tried to set up a local LOGON server to mimic the behavior of the demo page, but for some reason it didn't serve the DM representation. I was discussing it with Stephan but with no success. I am aware that there are other options but that project of mine ended so I didn't try anything else.

**Comment by goodmami** [comment]
@ZhaofengWu thank you for the follow-up. I'm sorry it didn't work out for you.

@wangxinyu0922 I hope you have better luck getting it to work!

Since DM-to-EDS conversion is not something I have planned for PyDelphin, I will close this issue.
