### ISSUE TITLE
REPP external groups are iterative?

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#254]
The wiki documentation is pretty clear that external group calls (such as `>wiki`) should only execute the group once while iterative groups get executed until they result in no changes, however as far as I can tell both the standalone REPP tool and ACE both execute external groups multiple times as well. The issue is a sentence like this:

```
# # Database administrative login by UNIX sockets local all postgres ident sameuser # TYPE DATABASE USER CIDR-ADDRESS METHOD
```

Both REPP and ACE remove both initial `#` characters with the following rule, which is part of `wiki.rpp` in the ERG:

```
!^ *[:*#]+
```

The wiki group is called from tokenizer.rpp like this:

```
>wiki
```

And that call is not inside of an iterative group. PyDelphin thus executes the group once, so it only removes the first `#` character. By commenting out that single rule, both REPP and ACE no longer remove either `#`, so I'm pretty sure that's the only rule that is causing the issue.

**Comment by goodmami** [comment]
It might not be an iterative external group call. Still need to confirm.

Here's a test system:

a.rpp
```
>b
:[ \t]+
```

b.rpp
```
!^ *[:*#]+						
```

a.set
```
repp-modules := a b.
repp-tokenizer := a.
repp-calls := a b.
```

Example:
```console
$ ~/logon/bin/repp -c repp/a.set <<< "# # hi"
hi
```

The simpler explanation could be that PyDelphin is not doing the match multiple times on the first pass, perhaps because it thinks the second match would overlap with the first.

**Comment by goodmami** [comment]
I just noticed that it doesn't overlap because of the `^` anchor, so it will only match the first one. Maybe this is a difference between Python's re module and PCRE?

**Comment by oepen** [comment]
i believe i have the same files as your test case, and i fail to reproduce the above:
```
$ cat a.rpp b.rpp a.set
>b
:[ \t]+
!^ *[:*#]+
repp-modules := a b.
repp-tokenizer := a.
repp-calls := a b.
$ echo '# # foo' | ~/src/logon/bin/repp -c ~/a.set
# # foo
```
the LKB, on the other hand, does seem to exhibit the troubling behaviour.  however, i notice in `repp.lsp`:
```
        else when (eq (fsr-type rule) :pop) do
          ;;
          ;; _fix_me_
          ;; i think we should not call external groups iteratively, they are
          ;; primarily there to modularize the rule set; if we actually wanted
          ;; to iterate an external group, the group call could be put into an
          ;; internal, numeric group.                            (3-feb-09; oe)
          ;;
```
so, more interestingly, why do you and i appear to see different results from the reference implementation?

**Comment by goodmami** [comment]
@oepen You need at least 1 tab after the `!` pattern in `b.rpp`, otherwise it doesn't seem to apply.

**Comment by goodmami** [comment]
Closing this as PyDelphin is doing the correct thing already. The ACE and PET implementations appear to be doing global substitution by re-running a regex match on the transformed string; if the substitution inserts nothing and the match is anchored to the start of the string, it will apply each time, which is not how regex substitution is supposed to happen.
