### ISSUE TITLE
Minor issues with REPP

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#308]
There are some parts of the REPP spec (spread across ReppTop wiki and various publications) that are not completely clear. PyDelphin currently makes guesses about the proper behavior, but it would be good to confirm them with others.

1. Must iterative groups be called within the module that defines them? (currently yes)
2. Can iterative group calls occur before the group's definition? (currently no, but maybe it should be allowed)
3. Must the tokenizer pattern appear in the top-level module (or included file)? Can it be defined in an external module instead? (currently no)
4. Is it an error to have tokenization patterns or meta-info declarations inside iterative groups? (currently no, probably should be yes)

**Comment by oepen** [comment]
thanks for the clarification request, mike!  i have tried to answer your questions in what i consider the official specification:

http://moin.delph-in.net/ReppTop?action=diff&rev2=44&rev1=43

do those changes seem sufficient to clarify your points?

**Comment by goodmami** [comment]
Yes, my questions are answered and I like the answers. Thanks!

**Comment by goodmami** [comment]
@oepen I'm working to make my code consistent with the updated spec, and it occurs to me there's another set of issues regarding iterative groups (which I'll call "internal" groups to be consistent with the wiki text). Extending my numbering from above...

5. Internal group definitions (considered atomically) are non-sequential; if the contents of internal groups must be sequential, then nesting of internal groups should not be allowed. By what logic should we allow nesting while disallowing meta-info/tokenizer definitions? (Note that I'm referring to the definitions, not the calls)
6. Assuming we allow nesting, then does the module-wide identifier space for internal groups persists *inside* internal groups, too? That is, both of these are illegal?
   ```
   #1
   ; ...
   #
   #1
   ; ...
   #
   ```

   and

   ```
   #1
   #1
   ; ...
   #
   #
   ```
7. If the answer to 6 is "yes", then can a nested internal group be called outside its parent group? E.g.:
   ```
   #1
   #2
   ; ...
   #
   #
   >2
   ```

I think the cleanest way to resolve these issues is to disallow nested internal group *definitions* while allowing nested calls. The problem is a potential break in backward compatibility.

Finally, I want to resolve some ambiguity around my use of "must" in (1) above. I think it is fine to define an internal group that is never called (like an inactive external group), but any internal group call must resolve to a group defined within the same module. Your text on the wiki is less ambiguous here.

**Comment by goodmami** [comment]
Coming back to this, here are things to do based on the wiki updates by Stephan:

- [x] Iterative groups must be called within the module that defines them (already done; maybe needs a test)
- [ ] Iterative group calls may occur before the group's definition
- [x] The tokenizer pattern must appear in the top-level module? (already done; may need a test)
- [ ] It is an error to have tokenization patterns or meta-info declarations inside an iterative groups
- [ ] Modules have one global namespace
  - iterative groups may not be repeated within a module
  - nested iterative group definitions are no different than flat definitions
