### ISSUE TITLE
Parameters for RDF codec

### ISSUE THREAD

**Issue by FredsoNerd** [delph-in/pydelphin#320]
Hello. I've been developing a parser from MRS to RDF, as part of a package. Recently, I noticed the possibility of expressing it as a delphin codec to be better used as part of the `delphin convert` command. For now, it works as a simple `cli` module.

The point is that this parser needs an extra parameter, such as _indexedmrs_. Even though rdf is recognized by the library as a codec, I wasn't able to use it from the command line, using `delphin convert -t rdf ...`, because I couldn't send this extra parameter.

Isn't there a way to solve this problem? Adding extra flags to the argparser, when initializing the module for example? I didn't find anything reading the documentation or codes.

**Comment by arademaker** [comment]
Hi @goodmami , @FredsoNerd works with me. He is implementing the code in http://github.com/arademaker/delph-rdf/. We want a plugin to convert all DELPH-IN representations to RDF. This is part of the goal of improving the WSI interface.

**Comment by goodmami** [comment]
Hello @FredsoNerd and @arademaker,

I think you're correct that there is currently no way to easily add an additional command-line option for codec plugins, and for now writing a new cli interface is your best bet.

However, I think what you're requesting sounds good in general, and this isn't the first time a codec needed something special. I wasn't happy to add the `--sem-i`, `--show-status`, or `--predicate-modifiers` options, but I didn't have a better solution. I can imagine some general purpose thing like `--options='properties=no show-status=no'`. Other ideas are welcome, too.

**Comment by goodmami** [comment]
I'll consider this question answered. Please reopen if you have further questions, or open a separate feature request if you want something like the general-purpose `--options` option.
