### ISSUE TITLE
DMRS XML encoding

### ISSUE THREAD

**Issue by arademaker** [delph-in/pydelphin#329]
where the XML encoding for DMRs were defined? I didn't find it in the docs.

**Comment by arademaker** [comment]
Do we have a DTD for that?

**Comment by arademaker** [comment]
Why the tag names such as post ? Why `realpred` and `gpred` instead of `surface predicate` (spred or something similar) and `abstract predicate` (apred) ?  why `rargname`? 

We may need namespaces to separate tags and attributes that are general to DMRS from the ones that are specific for grammars (TENSE, PROG, PREF)?

**Comment by goodmami** [comment]
For all your questions, see the DTD here:

http://svn.emmtee.net/trunk/lingo/lkb/src/rmrs/dmrs.dtd

This was designed by Ann, I think, so I cannot comment on the design decisions, although I believe it was based on the previous MRS and RMRS DTDs.

**Comment by arademaker** [comment]
Thank you @goodmami , I guess I would never find those files without your help! BTW, your comments about our RDF schemas would be valuable!!
