### ISSUE TITLE
scoped MRS

### ISSUE THREAD

**Issue by arademaker** [delph-in/pydelphin#332]
I just asked @john-a-carroll about the LKB code for generate the scoped MRS where from a single MRS we can produce many possible full scoped resolved interpretations (nesting of quantifiers, as far as I got). Maybe adding the code here would be relevant? If so, where?

**Comment by goodmami** [comment]
These would go in `delphin.scope`, but I believe this feature is already covered by #241 and #221. Or are you requesting something different?

**Comment by goodmami** [comment]
After further discussion, I believe this issue is a duplicate of #221, so I will close this one.
