### ISSUE TITLE
install `-e`

### ISSUE THREAD

**Issue by arademaker** [delph-in/pydelphin#389]
```batch
% pip install -e . 
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /Users/ar/r/pydelphin
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

need to udpate 

https://pydelphin.readthedocs.io/en/latest/guides/setup.html

**Comment by goodmami** [comment]
Please upgrade your version of pip: `pip install --upgrade pip`

As of version [21.3](https://pip.pypa.io/en/stable/news/#v21-3) (which is over 2 years old now), pip can install in editable mode for PEP-660-compatible backends, such as Hatch.

**Comment by arademaker** [comment]
indeed, sorry.

**Comment by goodmami** [comment]
No worries. Sometimes I also find myself ignoring pip's incessant warnings to upgrade itself.

And thanks for raising issues as you come across problems!
