### ISSUE TITLE
REPP tokenizer

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#43]
Make a module that reads `.repp` files and tokenizes strings, without firing up a parser. See here: http://moin.delph-in.net/ReppTop

**Comment by alvations** [comment]
+1 Reading `.repp` files will be a good first step =)

From Rebecca's [code](https://gist.github.com/alvations/99354d0fbe294c14cf7f), reading the LISP `.rpp` setting files seems to involve some boost regex compilation (`boost::make_u32regex`). Do you know whether they achieve the same regexes as python `re.compile`? More questions on http://stackoverflow.com/questions/34048609/converting-c-boost-regexes-to-python-re-regexes

**Comment by goodmami** [comment]
The ReppTop page says the LKB uses a different regex engine, but both are
Perl compatible. Rather than Python's re module, the 'regex' module seems
like it has better Perl compatibility.
