### ISSUE TITLE
tdl parse_* functions should not be part of the public API

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#81]
`tdl.parse()` is the user-facing function, but the other `tdl.parse_*` functions should not be. For backwards compatibility they should be available but deprecated, but the actual functions should be renamed and no longer documented.

Old version:

> The `tdl.parse()` function accepts a file stream, but the other parsing functions (e.g. `parse_typedef()`) require a deque of lexed tokens. If the other parsing functions remain publicly available, they should accept strings (maybe a pseudo-private version (e.g. `_parse_typedef()`) can accept the deque as it is now).

**Comment by goodmami** [comment]
> For backwards compatibility they should be available but deprecated, but the actual functions should be renamed and no longer documented.

Actually, they aren't documented already, they just have "public" names. It probably wouldn't be an issue to just make them private without deprecations (but with a suitable notice in the changelog).

In addition to the `parse_*` functions, `lex()` and `tokenize()` probably don't need to be public, but don't change them just yet. `lex()` is currently the only way to get at TDL comments, which may be useful for things like [ltdb](https://github.com/fcbond/ltdb).

**Comment by mcmillanmajora** [comment]
Re: making `tokenize()` private, `tdl_test.md` has an example showing the functionality of `tdl.tokenize()`. Should this be removed?

**Comment by goodmami** [comment]
When `tokenize()` is made non-public, its corresponding unit test can be removed (or de-emphasized, i.e, moved to a regular `.py` test file), but notice that I said not to make `tokenize()` or `lex()` non-public yet, as (at least for the latter) there is a plausible use case that wouldn't be covered if it were removed. For now just focus on the `parse_*` functions.
