### ISSUE TITLE
Mac Parsing on Ace

### ISSUE THREAD

**Issue by martsen79** [delph-in/pydelphin#95]
Described here: https://github.com/delph-in/pydelphin/wiki/Troubleshooting

**Comment by goodmami** [comment]
Copying here in case the wiki content goes away:

-----

If you are parsing on a Mac using Ace 0.9.24 and PyDelphin 0.6.0, you may encounter an error on parsing:

```python
> ace.parse('/Users/David/Documents/School/DELPH-IN/erg/erg-1214-osx-0.9.24.dat', 'The man jumped.')
```

The error of the following type

```python
> delphin.lib.pegre.PegreChoiceError: At position 0: 
>   At position 0: 
>   At position 0: Expected to match: -?(0|[1-9]\d*)(\.\d+[eE][-+]?|\.|[eE][-+]?)\d+
>   At position 0: Expected to match: -?\d+
>   At position 0: 
>   At position 0: Expected to match: "[^"\\]*(?:\\.[^"\\]*)*"
>   At position 0: Expected to match: (?:[^"\s\(\)\[\]\{\}\\;]+|\\.)+
>   At position 12: Expected to match: \)\s*
```

may be solved by adding to the parse command tsdbinfo=False, e.g.

```python
> ace.parse('/Users/David/Documents/School/DELPH-IN/erg/erg-1214-osx-0.9.24.dat', 'The man jumped.', tsdbinfo=False)
```

The presumed source of the error (under investigation) is interleaving the stdout and stderr of the Ace parser.

**Comment by goodmami** [comment]
Just confirming that I do not see this on Linux with the same versions of ACE, PyDelphin, or the ERG:

```python
>>> res = ace.parse('/home/goodmami/grammars/erg-1214-x86-64-0.9.24.dat', 'The man jumped.')
>>> len(res.results())
2
```
